// <auto-generated />
using CafeMenu_API_.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CafeMenu_API_.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220609171439_cafemenu")]
    partial class cafemenu
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CafeMenu_API_.Controllers.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Timeslot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "11",
                            ImgUrl = "https://www.etestware.com/wp-content/uploads/2020/12/shutterstock_515285995-1200x580.jpg",
                            Name = "1111",
                            Price = 1200L,
                            Stock = 80,
                            Timeslot = "afternoon",
                            Type = "a"
                        },
                        new
                        {
                            Id = 2,
                            Description = "333",
                            ImgUrl = "https://www.etestware.com/wp-content/uploads/2020/12/shutterstock_515285995-1200x580.jpg",
                            Name = "2222",
                            Price = 800L,
                            Stock = 100,
                            Timeslot = "afternoon",
                            Type = "b"
                        },
                        new
                        {
                            Id = 3,
                            Description = "333",
                            ImgUrl = "https://www.etestware.com/wp-content/uploads/2020/12/shutterstock_515285995-1200x580.jpg",
                            Name = "333",
                            Price = 1000L,
                            Stock = 50,
                            Timeslot = "afternoon",
                            Type = "c"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
